### PR TITLE
Hey 

### PR DESCRIPTION
**Pull request by UpperLEFTY**
Sorry I was reviewing your awesome portfolio, I spotted a typo that can break your site. 
I hope you'll accept the changes. Great work!

Bug: [assests]  fix: [assets]

### CODE REVIEW

**Comment by UpperLEFTY** [comment]
I'll fix the build, and do a new PR

**Comment by vvHacker007** [comment]
Hey there, I tried approving your changes but unfortunately, all the checks failed. But thank you for investing your time in trying to fix the bugs in my project.

**Comment by vvHacker007** [comment]
Sure, try your best!

**Comment by UpperLEFTY** [comment]
I pushed out new changes.

**Pull request closed without merging**
